image carousel
spencer-rafada/things-to-do-in-Rexburg pull request #6
Opened 2023-03-20 18:30 UTC by ckcomin

2023-03-21 03:02 UTC, spencer-rafada commented on src/index.html
Looks great!

2023-03-21 03:03 UTC, spencer-rafada commented on src/mjs/main.js
Don't forget to run **npm run format** before committing next time. Great job on the carousel!

2023-03-21 03:07 UTC, spencer-rafada requested changes
The carousel looks great! I have not been able to explain this before, but you can merge new versions of main to your branch when we make changes to main while you are working on your branch and have not finished it. I'll gladly walk you through this process one of these days if you are free!

2023-03-21 03:07 UTC, spencer-rafada commented on src/styles/global.css
Can you merge our main branch right now so the styles won't be a problem with vite? If you need help with this, contact me and I can help you!

The steps will usually be:
1. Go to your branch
2. On your console, write git merge main
3. Then you will resolve all of the conflicts from main to your branch.

2023-03-21 18:06 UTC, ckcomin commented on src/styles/global.css
Okay I just did it

2023-03-21 18:07 UTC, ckcomin commented on src/mjs/main.js
I ran the npm run format and i got "[error] No files matching the pattern were found: "'./**/*.{js,jsx,ts,tsx,css,md,json}'"."
This error also shows on the main.

2023-03-22 16:30 UTC, spencer-rafada commented on src/mjs/main.js
That just means there's no file types like that in the repository. That's fine.

2023-03-22 16:32 UTC, spencer-rafada commented on src/styles/global.css
Thank you! Lastly, make sure all the JavaScript file in the mjs folder are placed inside the js folder and linked correctly in the HTML. Besides that, everything else looks good.

2023-03-22 17:35 UTC, spencer-rafada approved these changes

2023-03-22 17:35 UTC, merged